default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: senac-tcs-api_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: senac-tcs-api_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  <<: *default
  database: senac-tcs-api_production
  username: test-api
  password: <%= ENV['TEST-API_DATABASE_PASSWORD'] %>
